function mimage(img)
%MIMAGE - show a two-dimensional image at its real dimensions
% MIMAGE(img) display the image without window crap etc.
% NKL 10.05.03
		
f = size(img);
figure(...
	'Position', [0 0 f(2) f(1)],...
	'menubar','none',...
	'color',[0 0 0],...
	'menubar','none', ...
	'toolbar','none', ...
	'doublebuffer','off', ...
	'backingstore','off', ...
	'integerhandle','off', ...
	'PaperPositionMode','auto',...
	'PaperType','A4','InvertHardCopy','off');
imagesc(img);
colormap(gray);
daspect([1 1 1]);
axis off;
set(gca, 'Units', 'normalized', 'Position', [0 0 1 1]);

